### ISSUE TITLE
能否提供一下 caffe.pb.h 和  caffe.pb.cc ？

### ISSUE THREAD

**Issue by pbdahzou** [junluan/shadow#1]
你好，能否提供一下 caffe.pb.h 和  caffe.pb.cc 吗？ 编译时，提示没有这两个文件，直接拷贝caffe里的不行。谢谢！

**Comment by pbdahzou** [comment]
你这个工作非常棒！

**Comment by junluan** [comment]
hi @pbdahzou 

caffe.pb.h 和 caffe.pb.cc 是由caffe.proto自动生成的，这边文档还没怎么写。
由于不同人提供的caffe训练模型对应的caffe.proto可能不一样（有人会魔改添加自己的layer），所以这边需要自己提供一个caffe.proto放到目录shadow/proto下面，和shadow.proto同级，cmake编译的时候会自动生成*.pb.h和*.pb.cc

**Comment by junluan** [comment]
@pbdahzou 
caffe.proto是在用`shadow/tools`下的c++代码转换模型的时候需要的，推理时不需要，你可以把这边 `option(BUILD_TOOLS "Build useful tools" ON)` 的选项改为OFF。

至于转换代码，现在可以用 `shadow/python` 下的脚本去处理，同样需要把caffe.proto生成的caffe_pb2.py放到 `shadow/python/proto` 下面
